// Shell styles that follow the palette. St's CSS has no variables, so the
// stylesheet is generated from the palette and swapped whenever it changes.

import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import St from 'gi://St';

Gio._promisify(Gio.File.prototype, 'replace_contents_bytes_async', 'replace_contents_finish');
Gio._promisify(Gio.File.prototype, 'delete_async');

/**
 * The palette-dependent part of Atelier's shell styles. Everything here
 * overrides a rule of stylesheet.css, which keeps the defaults; the extra
 * class in each selector makes these rules win regardless of load order.
 *
 * @param {object} p - palette
 * @returns {string} CSS
 */
export function paletteStylesheet(p) {
    const d = p.dark; // the switcher and the island are always dark
    return `/* Generated by Atelier from the palette ${p.source} (${p.variant}). */
.atelier-switcher .atelier-card:selected { border-color: ${d.primary}; }
.atelier-switcher .atelier-badge { background-color: ${d.primary}; color: ${d.onPrimary}; }
.atelier-switcher .atelier-dot { background-color: ${d.primary}; }
.atelier-switcher .atelier-chip { background-color: ${d.surfaceContainerHigh}; color: ${d.onSurfaceVariant}; }
.atelier-switcher .atelier-tab:checked { background-color: ${d.primaryContainer}; color: ${d.onPrimaryContainer}; }
.atelier-island .atelier-island-unread { background-color: ${d.primary}; }
.atelier-island .atelier-glance-power:focus { box-shadow: inset 0 0 0 2px ${d.primary}; }
.atelier-island .atelier-glance-day:today .atelier-glance-day-number { background-color: ${d.primary}; color: ${d.onPrimary}; }
.atelier-island .atelier-glance-event-bar { background-color: ${d.primary}; }
.atelier-island .atelier-power-tile:focus { border-color: ${d.primary}; }
.atelier-island .atelier-toast-check { color: ${d.primary}; }
`;
}

export class ThemeManager {
    constructor() {
        this._file = null;
        this._serial = 0;
        this._destroyed = false;
        this._dir = GLib.build_filenamev([GLib.get_user_cache_dir(), 'atelier']);
    }

    /**
     * Load the styles for a palette, replacing the previous ones.
     *
     * @param {object} palette
     * @returns {Promise<void>}
     */
    async update(palette) {
        const css = paletteStylesheet(palette);
        const hash = GLib.compute_checksum_for_string(GLib.ChecksumType.SHA1, css, -1).slice(0, 12);
        const name = `shell-${hash}.css`;
        if (this._file?.get_basename() === name)
            return;

        const serial = ++this._serial;
        GLib.mkdir_with_parents(this._dir, 0o755);
        // A new name each time: St caches stylesheets by file.
        const file = Gio.File.new_for_path(GLib.build_filenamev([this._dir, name]));
        await file.replace_contents_bytes_async(new GLib.Bytes(new TextEncoder().encode(css)),
            null, false, Gio.FileCreateFlags.REPLACE_DESTINATION, null);
        if (serial !== this._serial || this._destroyed) {
            file.delete_async(GLib.PRIORITY_DEFAULT, null).catch(() => {});
            return;
        }

        const theme = St.ThemeContext.get_for_stage(global.stage).get_theme();
        this._unload(theme);
        theme.load_stylesheet(file);
        this._file = file;
    }

    destroy() {
        this._destroyed = true;
        this._unload(St.ThemeContext.get_for_stage(global.stage).get_theme());
    }

    _unload(theme) {
        if (!this._file)
            return;
        theme.unload_stylesheet(this._file);
        this._file.delete_async(GLib.PRIORITY_DEFAULT, null).catch(() => {});
        this._file = null;
    }
}
