// Coloring GTK apps: Atelier writes the user stylesheets
// ~/.config/gtk-4.0/gtk.css and ~/.config/gtk-3.0/gtk.css. GTK reads them when
// an app starts. They can import a GTK 4 theme (libadwaita ignores the
// gtk-theme setting) and tint libadwaita's colors with the palette.
//
// Files are only written when they don't exist or were written by Atelier
// (recognized by their first line); anything else is left alone.
// Shared by the shell and the tests: only GLib/Gio may be used here.

import Gio from 'gi://Gio';
import GLib from 'gi://GLib';

Gio._promisify(Gio.File.prototype, 'query_info_async');
Gio._promisify(Gio.File.prototype, 'load_contents_async');
Gio._promisify(Gio.File.prototype, 'replace_contents_bytes_async', 'replace_contents_finish');
Gio._promisify(Gio.File.prototype, 'delete_async');

export const MARKER = '/* Generated by Atelier.';
const HEADER = `${MARKER} It is rewritten when the palette or the profile changes.
   Turn off "Color GTK apps" and GTK 4 theming in Atelier's settings to stop it. */`;

// How strongly libadwaita's surfaces take on the palette's hue.
const TINT = {vibrant: 0.1, muted: 0.06, monochrome: 0};

// libadwaita 1.7 surfaces, as named colors that differ between light and
// dark. Tinting them (instead of replacing them) keeps light and dark
// working without media queries, which GTK 4.18 doesn't support.
const SURFACES = [
    'window_bg_color', 'view_bg_color', 'headerbar_bg_color', 'headerbar_backdrop_color',
    'sidebar_bg_color', 'sidebar_backdrop_color', 'secondary_sidebar_bg_color',
    'popover_bg_color', 'dialog_bg_color', 'thumbnail_bg_color',
];

const fn = (...parts) => GLib.build_filenamev(parts);

/** @returns {string} ~/.config/gtk-4.0 */
export function gtk4ConfigDir() {
    return fn(GLib.get_user_config_dir(), 'gtk-4.0');
}

/** @returns {string} ~/.config/gtk-3.0 */
export function gtk3ConfigDir() {
    return fn(GLib.get_user_config_dir(), 'gtk-3.0');
}

/**
 * The GTK 4 stylesheet of a theme to import, matching the light/dark style.
 *
 * @param {string} themeDir - a theme directory with a gtk-4.0 folder
 * @param {boolean} dark
 * @returns {string|null} path of the stylesheet, or null if there is none
 */
export function themeStylesheet(themeDir, dark) {
    if (!themeDir)
        return null;
    const darkCss = fn(themeDir, 'gtk-4.0', 'gtk-dark.css');
    const css = fn(themeDir, 'gtk-4.0', 'gtk.css');
    if (dark && GLib.file_test(darkCss, GLib.FileTest.EXISTS))
        return darkCss;
    return GLib.file_test(css, GLib.FileTest.EXISTS) ? css : null;
}

/**
 * @param {string} themeDir
 * @returns {boolean} whether the theme ships a GTK 4 stylesheet
 */
export function hasGtk4Support(themeDir) {
    return Boolean(themeDir) && GLib.file_test(fn(themeDir, 'gtk-4.0', 'gtk.css'), GLib.FileTest.EXISTS);
}

/**
 * @param {object} options
 * @param {string|null} [options.themeCss] - theme stylesheet to import
 * @param {object|null} [options.palette] - palette to tint libadwaita with
 * @returns {string|null} the GTK 4 user stylesheet, or null for none
 */
export function gtk4Stylesheet({themeCss = null, palette = null}) {
    if (!themeCss && !palette)
        return null;
    const lines = [HEADER, ''];
    if (themeCss)
        lines.push(`@import url("${GLib.filename_to_uri(themeCss, null)}");`, '');
    if (palette) {
        // The light scheme's primary is a mid tone that works as accent
        // background in both styles; libadwaita derives the rest from it.
        const accent = palette.light.primary;
        const tint = TINT[palette.variant] ?? TINT.vibrant;
        lines.push(':root {',
            `  --accent-bg-color: ${accent};`,
            `  --accent-fg-color: ${palette.light.onPrimary};`);
        if (tint > 0) {
            for (const name of SURFACES)
                lines.push(`  --${name.replace(/_/g, '-')}: mix(@${name}, ${accent}, ${tint});`);
        }
        lines.push('}');
    }
    return `${lines.join('\n')}\n`;
}

/**
 * @param {object} options
 * @param {object|null} [options.palette]
 * @returns {string|null} the GTK 3 user stylesheet, or null for none
 */
export function gtk3Stylesheet({palette = null}) {
    if (!palette)
        return null;
    const accent = palette.light.primary;
    const onAccent = palette.light.onPrimary;
    return `${HEADER}

@define-color theme_selected_bg_color ${accent};
@define-color theme_selected_fg_color ${onAccent};
@define-color accent_bg_color ${accent};
@define-color accent_fg_color ${onAccent};
@define-color accent_color ${accent};
`;
}

async function inspect(path) {
    try {
        const info = await Gio.File.new_for_path(path).query_info_async(
            'standard::type,standard::is-symlink,standard::symlink-target',
            Gio.FileQueryInfoFlags.NOFOLLOW_SYMLINKS, GLib.PRIORITY_DEFAULT, null);
        const isSymlink = info.get_is_symlink();
        return {exists: true, isSymlink, target: isSymlink ? info.get_symlink_target() : null};
    } catch {
        return {exists: false, isSymlink: false, target: null};
    }
}

async function readText(path) {
    const [bytes] = await Gio.File.new_for_path(path).load_contents_async(null);
    return new TextDecoder().decode(bytes);
}

/**
 * Write (or remove) one user stylesheet.
 *
 * @param {string} path
 * @param {string|null} css - new contents; null removes Atelier's file
 * @param {object} [options]
 * @param {string|null} [options.legacyTarget] - target of a symlink BG Changer
 *   made at this path; such a link is replaced
 * @returns {Promise<{ok: boolean, changed: boolean, reason?: string}>}
 */
export async function writeStylesheet(path, css, {legacyTarget = null} = {}) {
    const file = Gio.File.new_for_path(path);
    let info = await inspect(path);

    if (info.isSymlink) {
        if (!legacyTarget || info.target !== legacyTarget)
            return {ok: false, changed: false, reason: `${path} is a link that Atelier didn't create`};
        await file.delete_async(GLib.PRIORITY_DEFAULT, null);
        info = {exists: false};
        if (css === null)
            return {ok: true, changed: true};
    }

    if (info.exists) {
        const current = await readText(path);
        if (!current.startsWith(MARKER))
            return {ok: false, changed: false, reason: `${path} already exists and wasn't written by Atelier`};
        if (css === null) {
            await file.delete_async(GLib.PRIORITY_DEFAULT, null);
            return {ok: true, changed: true};
        }
        if (current === css)
            return {ok: true, changed: false};
    } else if (css === null) {
        return {ok: true, changed: false};
    }

    GLib.mkdir_with_parents(GLib.path_get_dirname(path), 0o700);
    await file.replace_contents_bytes_async(new GLib.Bytes(new TextEncoder().encode(css)),
        null, false, Gio.FileCreateFlags.REPLACE_DESTINATION, null);
    return {ok: true, changed: true};
}

/**
 * Remove the assets link BG Changer made next to gtk.css; imports resolve
 * a theme's assets relative to the imported file, so it isn't needed.
 *
 * @param {string} dir - ~/.config/gtk-4.0
 * @param {string|null} legacyTarget
 * @returns {Promise<boolean>} whether the link was removed
 */
export async function removeLegacyAssetsLink(dir, legacyTarget) {
    if (!legacyTarget)
        return false;
    const path = fn(dir, 'assets');
    const info = await inspect(path);
    if (!info.isSymlink || info.target !== legacyTarget)
        return false;
    await Gio.File.new_for_path(path).delete_async(GLib.PRIORITY_DEFAULT, null);
    return true;
}

/**
 * @param {Gio.Settings} settings - Atelier's settings
 * @returns {{'gtk.css'?: string, assets?: string}} links BG Changer created
 */
export function legacyLinks(settings) {
    try {
        const state = JSON.parse(settings.get_string('gtk4-link') || '{}');
        return state?.links && typeof state.links === 'object' ? state.links : {};
    } catch {
        return {};
    }
}
